name: test_platform_view

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TestPlatformViewPlugin
        fileName: test_platform_view.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"